<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/lib/global-settings.php';

function updateAdminIp($ip, $subnet, $gateway, $name){
    $data = array(
        'ip' => $ip,
        'subnet' => $subnet,
        'gateway' => $gateway,
        'hostname' => $name
    );
    
    file_put_contents(
        config::getConfigDir() . config::adminIpSettings, 
        json_encode($data, JSON_PRETTY_PRINT),
        LOCK_EX
    );

    // If we have root permission, update hostname
    if (function_exists('posix_getuid') && posix_getuid() === 0) {
        @file_put_contents('/etc/hostname', $name);
        @shell_exec('hostname ' . escapeshellarg($name));
    }

    require_once $_SERVER['DOCUMENT_ROOT'] . '/lib/publish.php';
    setPendingChanges();
}

function getAdminSettings() {
    $file = config::getConfigDir() . config::adminIpSettings;
    if (file_exists($file)) {
        return json_decode(file_get_contents($file), true);
    }
    return array('ip' => '', 'subnet' => '', 'gateway' => '', 'hostname' => '');
}

function writeKeepalivedConfig($vip, $interface = 'eth0', $role = 'MASTER', $router_id = 51, $priority = 101, $reload = false) {
    $cfgPath = config::getKeepalivedCfg();
    
    $configContent = "# Generated by OSBal\n";
    $configContent .= "vrrp_instance VI_1 {\n";
    $configContent .= "    state " . ($role === 'MASTER' ? 'MASTER' : 'BACKUP') . "\n";
    $configContent .= "    interface " . escapeshellcmd($interface) . "\n";
    $configContent .= "    virtual_router_id " . intval($router_id) . "\n";
    $configContent .= "    priority " . intval($priority) . "\n";
    $configContent .= "    advert_int 1\n";
    $configContent .= "    authentication {\n";
    $configContent .= "        auth_type PASS\n";
    $configContent .= "        auth_pass osbal_vrrp\n";
    $configContent .= "    }\n";
    $configContent .= "    virtual_ipaddress {\n";
    $configContent .= "        " . escapeshellcmd($vip) . "\n";
    $configContent .= "    }\n";
    $configContent .= "}\n";

    if ($reload) {
        require_once $_SERVER['DOCUMENT_ROOT'] . '/lib/system.php';
        ApplianceSystem::reloadKeepalived();
    }
}
?>
