<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/lib/global-settings.php';

function getServicesFile() {
    return config::getConfigDir() . config::lbServices;
}

function getServices() {
    $file = getServicesFile();
    if (!file_exists($file)) {
        return array();
    }
    $content = file_get_contents($file);
    $data = json_decode($content, true);
    return is_array($data) ? $data : array();
}

function saveServices($services) {
    file_put_contents(getServicesFile(), json_encode($services, JSON_PRETTY_PRINT), LOCK_EX);
    compileHaproxyConfig($services);
}

function createService($name, $ip, $port, $mode = 'http', $balance = 'roundrobin') {
    $services = getServices();
    $id = uniqid();
    $services[$id] = array(
        'id' => $id,
        'name' => $name,
        'ip' => $ip,
        'port' => $port,
        'mode' => $mode,
        'balance' => $balance,
        'servers' => array()
    );
    saveServices($services);
    return $id;
}

function updateService($id, $name, $ip, $port, $mode, $balance) {
    $services = getServices();
    if (isset($services[$id])) {
        $services[$id]['name'] = $name;
        $services[$id]['ip'] = $ip;
        $services[$id]['port'] = $port;
        $services[$id]['mode'] = $mode;
        $services[$id]['balance'] = $balance;
        saveServices($services);
        return true;
    }
    return false;
}

function deleteService($id) {
    $services = getServices();
    if (isset($services[$id])) {
        unset($services[$id]);
        saveServices($services);
        return true;
    }
    return false;
}

function addServerToService($serviceId, $serverName, $serverIp, $serverPort, $weight = 1, $check = true) {
    $services = getServices();
    if (isset($services[$serviceId])) {
        $serverId = uniqid();
        $services[$serviceId]['servers'][$serverId] = array(
            'id' => $serverId,
            'name' => $serverName,
            'ip' => $serverIp,
            'port' => $serverPort,
            'weight' => $weight,
            'check' => $check
        );
        saveServices($services);
        return $serverId;
    }
    return false;
}

function removeServerFromService($serviceId, $serverId) {
    $services = getServices();
    if (isset($services[$serviceId]) && isset($services[$serviceId]['servers'][$serverId])) {
        unset($services[$serviceId]['servers'][$serverId]);
        saveServices($services);
        return true;
    }
    return false;
}

function compileHaproxyConfig($services = null) {
    if ($services === null) {
        $services = getServices();
    }

    $cfg = "# Generated by OSBal Loadbalancer Manager\n\n";
    
    // Global Section
    $cfg .= "global\n";
    $cfg .= "    log /dev/log local0\n";
    $cfg .= "    log /dev/log local1 notice\n";
    $cfg .= "    chroot /var/lib/haproxy\n";
    $cfg .= "    user haproxy\n";
    $cfg .= "    group haproxy\n";
    $cfg .= "    daemon\n\n";

    // Defaults Section
    $cfg .= "defaults\n";
    $cfg .= "    log     global\n";
    $cfg .= "    mode    http\n";
    $cfg .= "    option  httplog\n";
    $cfg .= "    option  dontlognull\n";
    $cfg .= "    timeout connect 5000\n";
    $cfg .= "    timeout client  50000\n";
    $cfg .= "    timeout server  50000\n\n";

    // Compile each service
    foreach ($services as $id => $service) {
        $frontName = "frontend_" . $id;
        $backName = "backend_" . $id;
        
        $bindIp = empty($service['ip']) ? '*' : $service['ip'];
        $bindPort = empty($service['port']) ? '80' : $service['port'];
        
        // Frontend configuration
        $cfg .= "frontend " . $frontName . "\n";
        $cfg .= "    bind " . $bindIp . ":" . $bindPort . "\n";
        $cfg .= "    mode " . ($service['mode'] === 'tcp' ? 'tcp' : 'http') . "\n";
        $cfg .= "    default_backend " . $backName . "\n\n";
        
        // Backend configuration
        $cfg .= "backend " . $backName . "\n";
        $cfg .= "    mode " . ($service['mode'] === 'tcp' ? 'tcp' : 'http') . "\n";
        
        // Balancing Strategy
        $strategy = $service['balance'];
        if ($strategy === 'cookie' && $service['mode'] !== 'tcp') {
            $cfg .= "    balance roundrobin\n";
            $cfg .= "    cookie SERVERID insert indirect nocache\n";
        } elseif ($strategy === 'ip') {
            $cfg .= "    balance source\n";
        } else {
            // Default to roundrobin
            $cfg .= "    balance roundrobin\n";
        }
        
        // Backend Servers
        foreach ($service['servers'] as $srvId => $srv) {
            $srvLine = "    server " . escapeshellcmd($srv['name']) . " " . escapeshellcmd($srv['ip']) . ":" . intval($srv['port']);
            
            if ($strategy === 'cookie' && $service['mode'] !== 'tcp') {
                $srvLine .= " cookie " . escapeshellcmd($srv['name']);
            }
            
            if ($srv['weight'] > 1) {
                $srvLine .= " weight " . intval($srv['weight']);
            }
            
            if ($srv['check']) {
                $srvLine .= " check";
            }
            
            $cfg .= $srvLine . "\n";
        }
        $cfg .= "\n";
    }

    $haproxyCfgPath = config::getHaproxyCfg();
    file_put_contents($haproxyCfgPath, $cfg, LOCK_EX);

    // Trigger reload of HAProxy if running as root
    if (function_exists('posix_getuid') && posix_getuid() === 0) {
        @shell_exec('systemctl reload haproxy');
    }
}
?>