<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/lib/global-settings.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/lib/system.php';

function getSslFile() {
    return config::getConfigDir() . config::sslFile;
}

function getSslCertificates() {
    $file = getSslFile();
    if (!file_exists($file)) {
        return array();
    }
    $content = file_get_contents($file);
    $data = json_decode($content, true);
    return is_array($data) ? $data : array();
}

function saveSslCertificates($certs) {
    file_put_contents(getSslFile(), json_encode($certs, JSON_PRETTY_PRINT), LOCK_EX);
    compileStunnelConfig($certs);
}

function getCertsDir() {
    $path = '/etc/stunnel/certs/';
    if (!is_dir($path) || !is_writable($path)) {
        // Fallback to sandbox config path
        $path = config::getConfigDir() . 'certs/';
        if (!file_exists($path)) {
            @mkdir($path, 0755, true);
        }
    }
    return $path;
}

function addCertificate($name, $certText, $keyText, $bindIp = '*', $bindPort = 443, $targetPort = 80) {
    $certs = getSslCertificates();
    
    // Combine Certificate and Private Key into a single PEM file (standard Stunnel format)
    $pemContent = trim($certText) . "\n\n" . trim($keyText) . "\n";
    $pemFileName = preg_replace('/[^a-zA-Z0-9_\-]/', '', $name) . '.pem';
    $pemFullPath = getCertsDir() . $pemFileName;
    
    file_put_contents($pemFullPath, $pemContent, LOCK_EX);
    
    $certs[$name] = array(
        'name' => $name,
        'pemPath' => $pemFullPath,
        'bindIp' => $bindIp,
        'bindPort' => intval($bindPort),
        'targetPort' => intval($targetPort)
    );
    
    saveSslCertificates($certs);
    return true;
}

function deleteCertificate($name) {
    $certs = getSslCertificates();
    if (isset($certs[$name])) {
        $pemPath = $certs[$name]['pemPath'];
        if (file_exists($pemPath)) {
            @unlink($pemPath);
        }
        unset($certs[$name]);
        saveSslCertificates($certs);
        return true;
    }
    return false;
}

function compileStunnelConfig($certs = null) {
    if ($certs === null) {
        $certs = getSslCertificates();
    }

    $cfg = "# Generated by OSBal Loadbalancer SSL Manager\n\n";
    
    // Global parameters (optimized for Debian/Ubuntu stunnel4)
    $cfg .= "chroot = /var/lib/stunnel4/\n";
    $cfg .= "setuid = stunnel4\n";
    $cfg .= "setgid = stunnel4\n";
    $cfg .= "pid = /stunnel4.pid\n\n";
    
    $cfg .= "socket = l:TCP_NODELAY=1\n";
    $cfg .= "socket = r:TCP_NODELAY=1\n\n";

    // Write service blocks
    foreach ($certs as $name => $cert) {
        $bindIp = empty($cert['bindIp']) ? '0.0.0.0' : $cert['bindIp'];
        if ($bindIp === '*') {
            $bindIp = '0.0.0.0';
        }
        
        $cfg .= "[ssl_" . preg_replace('/[^a-zA-Z0-9_\-]/', '', $name) . "]\n";
        $cfg .= "client = no\n";
        $cfg .= "accept = " . $bindIp . ":" . intval($cert['bindPort']) . "\n";
        $cfg .= "connect = 127.0.0.1:" . intval($cert['targetPort']) . "\n";
        $cfg .= "cert = " . $cert['pemPath'] . "\n\n";
    }

    $stunnelCfgPath = config::getStunnelCfg();
    file_put_contents($stunnelCfgPath, $cfg, LOCK_EX);

    // Trigger stunnel restart
    ApplianceSystem::restartStunnel();
}
?>
